-- ==========================================================
-- PROJECT: Institutional Equity Risk & Analytics System
-- DATABASE: Oracle 21c (XE)
-- PURPOSE: Schema for NIFTY 50 Time-Series Data & Risk Metrics
-- ==========================================================

-- 1. ASSETS TABLE (Dimension Table)
-- Stores metadata for companies in the NIFTY 50 universe.
CREATE TABLE ASSETS (
    TICKER VARCHAR2(20) PRIMARY KEY,
    COMPANY_NAME VARCHAR2(255) NOT NULL,
    SECTOR VARCHAR2(100),
    ASSET_TYPE VARCHAR2(50) DEFAULT 'Equity'
);

-- 2. MARKETDATA TABLE (Fact Table)
-- Stores 5+ years of historical OHLCV data (~60,000+ records).
CREATE TABLE MARKETDATA (
    DATA_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TICKER VARCHAR2(20) NOT NULL,
    PRICE_DATE DATE NOT NULL,
    OPEN_PRICE NUMBER(15, 4),
    CLOSE_PRICE NUMBER(15, 4),
    VOLUME NUMBER(20),
    -- Referential Integrity: Ensures prices only exist for registered assets.
    CONSTRAINT FK_TICKER FOREIGN KEY (TICKER) REFERENCES ASSETS(TICKER)
);

-- 3. RISKMETRICS TABLE (Analytical Table)
-- Stores pre-computed quantitative coefficients for real-time dashboarding.
CREATE TABLE RISKMETRICS (
    TICKER VARCHAR2(20) PRIMARY KEY,
    BETA NUMBER(10, 4),           -- Systematic Risk (CFA Concept)
    SHARPE_RATIO NUMBER(10, 4),   -- Risk-Adjusted Return (CFA Concept)
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RISK_TICKER FOREIGN KEY (TICKER) REFERENCES ASSETS(TICKER)
);

-- 4. PERFORMANCE INDEXING
-- Optimizes query speed for the Dashboard.
CREATE INDEX IDX_TICKER_DATE ON MARKETDATA(TICKER, PRICE_DATE);
